Overhaul of bluetooth connection to accommodate for user-friendliness of both windows and mac installations
teamhart-nl/backend pull request #39
Opened 2022-02-08 16:21 UTC by rdvhoorn

Previously, winreg was used to initiate a Bluetooth connection from windows devices. This is no longer necessary. 

-Winreg completely removed from code
-Added automatic Bluetooth pairing capability for MAC (not tested on Linux)
-Moved `distribution` parameter to definitions.py
-Added `RUNNING_ON_MAC` to definitions.py
-Rewrote README
-Reworked initialization of server and routes.
-Reworked `requirements.txt` to only show needed packages.

Note: the changes in the Routes.py file seem very drastic but is only like indented once as it is now encompassed in an outer 'initialization' function which is called by the app.py script.

2022-02-08 16:46 UTC, hendriklohse commented on README.md
> +9. Activate the environment: `.\backend\Scripts\activate`
For mac this is: backend/bin/activate

2022-02-08 17:00 UTC, hendriklohse commented on README.md
> +10. Check if activation worked: `where python` should return `...\<root>\venv\backend\Scripts\python.exe`
For mac 'where' is not a command. I think the more general approach here is to do:
echo $VIRTUAL_ENV
This will return '.../<root>/venvs/backend'
Once you run deactivate / leave the virtual environment, the $VIRTUAL_ENV variable will be cleared/empty.

source: https://stackoverflow.com/questions/1871549/determine-if-python-is-running-inside-virtualenv
The answer from @florisla (4th) gives a nice overview of all possible methods.

2022-02-08 17:08 UTC, hendriklohse commented on README.md
>  # backend
General remark:
There is no consistency regarding the use of '\' (windows) and '/' (mac). If we want one general installation I'd opt for '\'.

2022-02-09 04:59 UTC, SanderSteeghs requested changes

2022-02-09 04:59 UTC, SanderSteeghs commented on README.md
> +  4. Set `RUNNING_ON_MAC` to True if you are running the software on a MAC or Linux machine
You should not need to define this in `definitions.py` but 
`import os
os.system()` 
can already tell you if you are `Windows` `Darwin` or `Linux`

2022-02-09 04:59 UTC, SanderSteeghs commented on src/modules/PrototypeConnection.py
> +        if mac is not None:
I always prefer invert the `if` to reduce the complexity.
Basically I return early when I can and prevent the `else` keyword as much as possible

2022-02-09 04:59 UTC, SanderSteeghs commented on src/modules/PrototypeConnection.py
> +                        # Mac has standardized ports. The names of the ports include the name of the bluetooth chip,
this function has a few too many indents and is hard to follow. Extract for example the part where you find the port when OS is mac.

2022-02-09 04:59 UTC, SanderSteeghs commented on README.md
> +  4. Set `RUNNING_ON_MAC` to True if you are running the software on a MAC or Linux machine
```suggestion
  4. Set `RUNNING_ON_MAC` to True if you are running the software on a MAC machine   
```
Linux is not supported right

2022-02-09 04:59 UTC, SanderSteeghs commented on README.md
> +10. Check if activation worked: `where python` should return `...\<root>\venv\backend\Scripts\python.exe`
`where` and `which` are commands in mac. 
How can the `$VIRTUAL_ENV` have a relative path? It is also not very reliable since one does not necessarily follow the `activate` the venv.
A more reliable method is to use hroncok's method within your `main.py`. This step can then also be removed from the readme

2022-02-09 04:59 UTC, SanderSteeghs commented on README.md
> +2. Make sure the boolean variables in definitions.py are set correctly:
Idealy, we create some `yaml`/`json`/`xml` config file instead of `definitions.py`. Then you can remove the documentation from here and move it to that file instead. Advantage of that is that when you update/add/remove the parameters to you app, you are more inclined to change the documentation too. Otherwise the readme and code might go out-of-sync

2022-02-09 04:59 UTC, SanderSteeghs commented on README.md
>  4. Change the links in the `index.html` referring to js/img/css files by adding the prefix `static/`
Outside of the score of this PR, but we could consider automating this with a script.

2022-02-09 04:59 UTC, SanderSteeghs commented on src/modules/PrototypeConnection.py
>          if not self.debug:
same as my comment below: if you invert this `if` statement, you can reduce the number of indents you need.
 ```suggestion
        if self.debug:
            Logger.log_info("PrototypeConnection initialized in debug mode.")
            return
        
        try:
            port = None 
        ...
```

2022-02-09 08:25 UTC, hendriklohse commented on README.md
> +10. Check if activation worked: `where python` should return `...\<root>\venv\backend\Scripts\python.exe`
hroncok's answer seems to be more robust indeed

2022-02-10 14:04 UTC, LourensT requested changes
Code is fine imo, but I cannot test the refactor of prototypeconnection\s bluetooth part.  If that is tested the PR can be merged imo.

2022-02-10 14:04 UTC, LourensT commented on src/routes/Routes.py
> +def init_views(app, dispatcher):
I might've missed why this refactor of putting everything in an init_views method is necessary, but nothing in the routes changed right? cus now it shows 500+ new lines

2022-02-10 14:13 UTC, rdvhoorn commented on README.md
> +10. Check if activation worked: `where python` should return `...\<root>\venv\backend\Scripts\python.exe`
I changed the line to just 'return the path of the virtualenvironment'. In addition i added some explanation at the top for more advanced users

2022-02-10 14:14 UTC, rdvhoorn commented on src/routes/Routes.py
> +def init_views(app, dispatcher):
Its necessary for the way that flask loads servers. Its a bit weird, but this seemed to work best.

2022-02-10 14:14 UTC, rdvhoorn commented on src/routes/Routes.py
> +def init_views(app, dispatcher):
But yes, that is the only thing that changed

2022-02-10 14:23 UTC, SanderSteeghs approved these changes
Nice job :-)

2022-02-10 15:47 UTC, rdvhoorn commented on src/modules/PrototypeConnection.py
> +                if os.name == 'nt': # Check if running on windows
you are correct lol good catch

2022-02-11 09:47 UTC, hendriklohse commented on src/modules/PrototypeConnection.py
> +                if os.name == 'nt': # Check if running on windows
Changed it

2022-02-11 09:56 UTC, hendriklohse approved these changes

2022-02-11 12:34 UTC, LourensT approved these changes
LGTM

2022-02-11 12:35 UTC, merged